# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in my_rust_gem.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"

gem "rake-compiler"

gem "test-unit", "~> 3.0"
