# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

require "rb_sys/extensiontask"

task build: :compile

GEMSPEC = Gem::Specification.load("my_rust_gem.gemspec")

RbSys::ExtensionTask.new("my_rust_gem", GEMSPEC) do |ext|
  ext.lib_dir = "lib/my_rust_gem"
end

task default: %i[compile test]
